# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rbaf_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RbafWin(object):
    def setupUi(self, RbafWin):
        RbafWin.setObjectName("RbafWin")
        RbafWin.resize(600, 480)
        RbafWin.setAcceptDrops(True)
        self.centralwidget = QtWidgets.QWidget(RbafWin)
        self.centralwidget.setObjectName("centralwidget")

        self.labelInvestmentScale = QtWidgets.QLabel(self.centralwidget)
        self.labelInvestmentScale.setGeometry(QtCore.QRect(10, 20, 100, 16))
        self.labelInvestmentScale.setObjectName("labelInvestmentScale")
        self.lineEditInvestmentScale = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditInvestmentScale.setGeometry(QtCore.QRect(120, 20, 113, 20))
        self.lineEditInvestmentScale.setObjectName("lineEditInvestmentScale")

        self.labelPositionRatio = QtWidgets.QLabel(self.centralwidget)
        self.labelPositionRatio.setGeometry(QtCore.QRect(10, 90, 100, 16))
        self.labelPositionRatio.setObjectName("labelPositionRatio")
        self.lineEditPositionRatio = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPositionRatio.setGeometry(QtCore.QRect(120, 90, 113, 20))
        self.lineEditPositionRatio.setObjectName("lineEditPositionRatio")

        self.labelRateOfReturn = QtWidgets.QLabel(self.centralwidget)
        self.labelRateOfReturn.setGeometry(QtCore.QRect(10, 160, 100, 16))
        self.labelRateOfReturn.setObjectName("labelRateOfReturn")
        self.lineEditRateOfReturn = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditRateOfReturn.setGeometry(QtCore.QRect(120, 160, 113, 20))
        self.lineEditRateOfReturn.setObjectName("lineEditRateOfReturn")

        self.labelAverageRateOfReturn = QtWidgets.QLabel(self.centralwidget)
        self.labelAverageRateOfReturn.setGeometry(QtCore.QRect(10, 230, 100, 16))
        self.labelAverageRateOfReturn.setObjectName("labelAverageRateOfReturn")
        self.lineEditAverageRateOfReturn = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditAverageRateOfReturn.setGeometry(QtCore.QRect(120, 230, 113, 20))
        self.lineEditAverageRateOfReturn.setObjectName("lineEditAverageRateOfReturn")

        self.labelAverageLossRate = QtWidgets.QLabel(self.centralwidget)
        self.labelAverageLossRate.setGeometry(QtCore.QRect(10, 300, 100, 16))
        self.labelAverageLossRate.setObjectName("labelAverageLossRate")
        self.lineEditAverageLossRate = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditAverageLossRate.setGeometry(QtCore.QRect(120, 300, 113, 20))
        self.lineEditAverageLossRate.setObjectName("lineEditAverageLossRate")

        self.labelAverageAccuracy = QtWidgets.QLabel(self.centralwidget)
        self.labelAverageAccuracy.setGeometry(QtCore.QRect(10, 370, 100, 16))
        self.labelAverageAccuracy.setObjectName("labelAverageAccuracy")
        self.lineEditAverageAccuracy = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditAverageAccuracy.setGeometry(QtCore.QRect(120, 370, 113, 20))
        self.lineEditAverageAccuracy.setObjectName("lineEditAverageAccuracy")

        self.pushButtonCalc = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCalc.setGeometry(QtCore.QRect(70, 420, 101, 31))
        self.pushButtonCalc.setObjectName("pushButtonCalc")

        self.tableWidgetOutput = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetOutput.setGeometry(QtCore.QRect(310, 30, 251, 351))
        self.tableWidgetOutput.setObjectName("tableWidgetOutput")
        self.tableWidgetOutput.setColumnCount(1)
        self.tableWidgetOutput.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOutput.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOutput.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOutput.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOutput.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOutput.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOutput.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOutput.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOutput.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOutput.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOutput.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOutput.setHorizontalHeaderItem(0, item)
        self.tableWidgetOutput.horizontalHeader().setCascadingSectionResizes(True)
        RbafWin.setCentralWidget(self.centralwidget)

        self.retranslateUi(RbafWin)
        QtCore.QMetaObject.connectSlotsByName(RbafWin)
        RbafWin.setTabOrder(self.lineEditInvestmentScale, self.lineEditPositionRatio)
        RbafWin.setTabOrder(self.lineEditPositionRatio, self.lineEditRateOfReturn)
        RbafWin.setTabOrder(self.lineEditRateOfReturn, self.lineEditAverageRateOfReturn)
        RbafWin.setTabOrder(self.lineEditAverageRateOfReturn, self.lineEditAverageLossRate)
        RbafWin.setTabOrder(self.lineEditAverageLossRate, self.lineEditAverageAccuracy)
        RbafWin.setTabOrder(self.lineEditAverageAccuracy, self.pushButtonCalc)
        RbafWin.setTabOrder(self.pushButtonCalc, self.tableWidgetOutput)

    def retranslateUi(self, RbafWin):
        _translate = QtCore.QCoreApplication.translate
        RbafWin.setWindowTitle(_translate("RbafWin", "RBAF计算器"))
        self.labelInvestmentScale.setText(_translate("RbafWin", "投资组合规模(万)"))
        self.labelPositionRatio.setText(_translate("RbafWin", "计划仓位比例(%)"))
        self.labelRateOfReturn.setText(_translate("RbafWin", "期望目标收益率(%)"))
        self.labelAverageRateOfReturn.setText(_translate("RbafWin", "历史平均收益率(%)"))
        self.labelAverageLossRate.setText(_translate("RbafWin", "历史平均亏损率(%)"))
        self.pushButtonCalc.setText(_translate("RbafWin", "RBAF计算"))
        item = self.tableWidgetOutput.verticalHeaderItem(0)
        item.setText(_translate("RbafWin", "成功投资的平均收益"))
        item = self.tableWidgetOutput.verticalHeaderItem(1)
        item.setText(_translate("RbafWin", "成功投资的数量"))
        item = self.tableWidgetOutput.verticalHeaderItem(2)
        item.setText(_translate("RbafWin", "失败投资的平均亏损"))
        item = self.tableWidgetOutput.verticalHeaderItem(3)
        item.setText(_translate("RbafWin", "失败投资的数量"))
        item = self.tableWidgetOutput.verticalHeaderItem(4)
        item.setText(_translate("RbafWin", "收益/风险比"))
        item = self.tableWidgetOutput.verticalHeaderItem(5)
        item.setText(_translate("RbafWin", "仓位大小"))
        item = self.tableWidgetOutput.verticalHeaderItem(6)
        item.setText(_translate("RbafWin", "预期每笔投资净收益率"))
        item = self.tableWidgetOutput.verticalHeaderItem(7)
        item.setText(_translate("RbafWin", "预期每笔投资净收益额"))
        item = self.tableWidgetOutput.verticalHeaderItem(8)
        item.setText(_translate("RbafWin", "目标金额"))
        item = self.tableWidgetOutput.verticalHeaderItem(9)
        item.setText(_translate("RbafWin", "所需投资数量"))
        item = self.tableWidgetOutput.horizontalHeaderItem(0)
        item.setText(_translate("RbafWin", "计算结果"))
        self.labelAverageAccuracy.setText(_translate("RbafWin", "平均交易成功率(%)"))
